# Generated by Django 3.2.5 on 2021-08-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='user',
            new_name='username',
        ),
    ]
